init

diff --git a/controllers/sbin/usbboot-init b/controllers/sbin/usbboot-init
--- a/controllers/sbin/usbboot-init
+++ b/controllers/sbin/usbboot-init
@@ -1,24 +1,104 @@
 #!/bin/bash
 
+
+# Load default config
+. /usr/share/clusterctrl/clusterctrl-conf-defaults
+
+# Then try to override with customised config
+if [ -f "/etc/default/clusterctrl" ]; then
+	. /etc/default/clusterctrl
+fi
+
+
+[ "$PS1" ] && return || exit;
+
+if [ ! -d "${OFS_LOWER_DIR}" ];then
+	echo "OverlayFS lower dir not found at $OFS_LOWER_DIR"
+	echo "Aborting"
+	[ "$PS1" ] && return || exit;
+fi
+
+
+
+
+
 if [ $# -ne 1 ]; then
- echo "Usage: $0 P"
- echo " where X is the pX number you to configure"
- echo " in the /var/lib/clusterctrl/nfs/pX/ directory."
- exit
+	echo "Usage: usbboot-init ${NODE_PRE}X"
+	echo " where X is the index of the node you wish to configure"
+
+	[ "$PS1" ] && return || exit;
+
 fi
 
-P=$1
+NODE=$1
 
-if [ ! -d "/var/lib/clusterctrl/nfs/p$P" ];then
- echo "Directory for p$P not found (/var/lib/clusterctrl/nfs/p$P)"
- exit
+
+
+if [ 1=0 ];then
+
+	# Create boot dir and populate with bootcode
+	mkdir -p "$BOOT_DIR"
+	ln -fs /boot/bootcode.bin "$BOOT_DIR"
+
+
+	# create folder
+	mkdir "$VFS_DIR/$NODE_PREFIX$NODE.etx4"
+
+	# create size-limited file
+	touch "$VFS_DIR/$NODE_PREFIX$NODE.etx4"
+
+	# fill with /dev/zero
+	dd if=/dev/zero of="$VFS_DIR/$NODE_PREFIX$NODE.etx4" status=progress iflag=count_bytes count="$VFS_SIZE"
+
+	# mkfs
+	mkfs.etx4 "$VFS_DIR/$NODE_PREFIX$NODE.etx4"
+
+	# mount vfs
+	echo "$VFS_DIR/$NODE_PREFIX$NODE.etx4    $OFS_DIR/$NODE_PREFIX$NODE/ ext4    rw,loop,usrquota,grpquota  0 0" | sudo tee -a /etc/fstab
+	sudo mount -a #"$VFS_DIR/$NODE_PREFIX$P.etx4
+
+	# mkdir {upper,work}
+	mkdir "$OFS_DIR/$NODE_PREFIX$NODE/{upper,work}"
+
+	# mount as OverlayFS
+	echo "overlay $NFS_DIR/$NODE_PREFIX$NODE/ overlay rw,relatime,lowerdir=$OFS_LOWER_DIR/,upperdir=$OFS_DIR/$NODE_PREFIX$NODE/upper,workdir=$OFS_DIR/$NODE_PREFIX$NODE/work 0 0" | sudo tee -a /etc/fstab
+
+
+	# Setup NFS exports for NFSROOT
+	echo "# ClusterCTRL exports for USB boot" >> $MNT/etc/exports
+	for ((P=1;P<=4;P++));do
+		echo "$NFS_DIR/$NODE_PREFIX$NODE 172.19.180.$P(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
+		mkdir "$NFS_DIR/$NODE_PREFIX$NODE/"
+	done
+
+
+
+	# Enable rpiboot for booting without SD cards
+	chroot $MNT systemctl enable clusterctrl-rpiboot
+	# Disable nfs server (rely on clusterctrl-rpiboot to start it if needed)
+	chroot $MNT systemctl disable nfs-kernel-server
 fi
 
-if [ ! -f "/var/lib/clusterctrl/nfs/p$P/usr/share/clusterctrl/reconfig-usbboot" ];then
- echo "Reconfigure script not found for p$P"
- echo "Have you downloaded and expanded the usbboot archive?"
- echo "See: https://clusterhat.com/setup-software"
- exit
+NFS_FULL_PATH=$NFS_DIR/$NODE_PREFIX$NODE
+
+if [ ! -d "${NFS_FULL_PATH}" ];then
+	echo "Directory for $NODE_PREFIX$NODE not found (${NFS_FULL_PATH})"
+	[ "$PS1" ] && return || exit;
 fi
 
-/var/lib/clusterctrl/nfs/p$P/usr/share/clusterctrl/reconfig-usbboot $P
+if [ -f "${FULL_DIR}/boot/cmdline.txt" ];then
+	sed -i "s#nfsroot=.*:static#nfsroot=172.19.180.254:${NFS_FULL_PATH} rw ip=172.19.180.$NODE:172.19.180.254::255.255.255.0:${NODE_PREFIX}$NODE:usb0.10:static#" "$NFS_FULL_PATH"/boot/cmdline.txt
+else
+	echo "Missing cmdline.txt file in node folder. Aborting"
+#	[ "$PS1" ] && return || exit;
+fi
+if [ -f "${FULL_DIR}/etc/dhcpcd.conf" ];then
+	sed -i "s+static ip_address=172.19.180.*/24 #ClusterCTRL+static ip_address=172.19.180.${NODE}/24 #ClusterCTRL+" "${NFS_FULL_PATH}"/etc/dhcpcd.conf
+else
+	echo "Missing dhcpcd.conf file in node folder. Aborting"
+#	[ "$PS1" ] && return || exit;
+fi
+echo "Finished setting up node in ${NFS_FULL_PATH}"
+
+
+
